# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kactivities': '@latest'
    'frameworks/kauth': '@latest'
    'frameworks/kcodecs': '@latest'
    'frameworks/kcompletion': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kcrash': '@latest'
    'frameworks/kdbusaddons': '@latest'
    'frameworks/kglobalaccel': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kidletime': '@latest'
    'frameworks/kio': '@latest'
    'frameworks/kjobwidgets': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/knotifyconfig': '@latest'
    'frameworks/kservice': '@latest'
    'frameworks/kwayland': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/kxmlgui': '@latest'
    'frameworks/solid': '@latest'
    'frameworks/kcmutils': '@latest' # kcmutils_generate_desktop_file
    'plasma/plasma-workspace': '@same'

- 'on': ['Linux']
  'require':
    'frameworks/bluez-qt': '@latest'
    'frameworks/networkmanager-qt': '@latest'
Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
