/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -p upower_interface /home/ltinkl/svn/KDE/kdebase/workspace/powerdevil/daemon/backends/upower/dbus/org.freedesktop.UPower.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "upower_interface.h"

/*
 * Implementation of interface class OrgFreedesktopUPowerInterface
 */

OrgFreedesktopUPowerInterface::OrgFreedesktopUPowerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopUPowerInterface::~OrgFreedesktopUPowerInterface()
{
}


#include "upower_interface.moc"
